name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - xeus-python
  - ipywidgets
  - matplotlib
  - tqdm
  - scipy
  - pip:
    - git+https://github.com/ulido/pymes
