name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core >=0.4.1,<0.5.0
  - jupyterlite-xeus>=2.0.0,<3
  - matplotlib
  - ipywidgets
  - tqdm
  - scipy
  - pip:
    - git+https://github.com/ulido/pymes
